server:  
  port: ${PORT:4343}

spring:  
  application:
    name: auth-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true

auth:
  issuer: AR-Auth
  header: X-Authorization
  token-type: Bearer
  #signing-key: ${SIGNING_KEY}
  signing-key: GQS7R0mLWs2N4ZF+t2bxipjrhWCPK40jh6Or60AowM0BNbxCQWywg4KZwkcEXPH4TeAuqiM3qCFQO1A/B5Djug==
  expires-in-sec: 7200
  compression-enabled: false